name = "Fabric Lite"
author = "NullBite"
version = "0.0.0-1.19.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8af40ff863fc17b9c1a011539bed64325ef847938c38b7cad1f96fc2d67f929d"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
