name = "Fabric Lite"
author = "NullBite"
version = "0.0.0-1.19.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9546e8545961886b61624a9252e1a59eb3cdf7342e3eeaf93a1d96a698688afc"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
