name = "Fabric Lite"
author = "NullBite"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d4d0603a1098506a9ea597701220604eb201299c6c46f51033b07acc0437652"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
