name = "Fabric Lite"
author = "NullBite"
version = "0.0.0-1.19.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1c1ed4a882c9c8ff440dee69989a47612a652111cf69b0046a0c6808b2c0e1c"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
