name = "Fabric Lite"
author = "NullBite"
version = "1.2.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c271047e2b7de918567251d1402eef489eed2a1eb81383c0bb12367efb369f3d"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
