name = "Fabric Server Lite"
author = "NullBite"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05d6519976546f97e6f3f8839c06c4a434c2375c1aec8582e3791b5973fe4cf9"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
