name = "Fabric Lite"
author = "NullBite"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f91b2ce3a23f51fe37d31b41fd75725571e465bc9fc57db6bf77d673e2ac4d5"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
