name = "Fabric Lite"
author = "NullBite"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2684a4bf4b00556a0863acbea64a5ba04272c541625d81b473654af3d93312ff"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
