name = "Fabric Lite"
author = "NullBite"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c649c6425065c7f3d6a312e22f3b9440dfdedb54578c83f4d525ffc5e5af4e75"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
