name = "Fabric Lite"
author = "NullBite"
version = "0.0.0-1.19.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "452b6d4291be21f1f067da9e31a819ed90afb4886446399fdcedb89ff9657b5d"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
