name = "Fabric Lite"
author = "NullBite"
version = "1.2.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5d9dbcde4d7f2af399270d4edfcb70e6bd939ff462c5427d67d850287761003"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
